
# 1. Tire ERP
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tire-erp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tire-erp
  template:
    metadata:
      labels:
        app: tire-erp
    spec:
      containers:
        - name: tire-erp
          image: ghcr.io/steve-shih/tire_erp-tire-erp:master
          imagePullPolicy: Always

          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: TIRE_ERP_MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: tire-erp
spec:
  selector:
    app: tire-erp
  ports:
    - port: 8000
      targetPort: 8000
---
# 2. FEEDING
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feeding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feeding
  template:
    metadata:
      labels:
        app: feeding
    spec:
      containers:
        - name: feeding
          image: ghcr.io/steve-shih/feeding-feeding:main

          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: feeding
spec:
  selector:
    app: feeding
  ports:
    - port: 3000
      targetPort: 3000
---
# 3. daynote-backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daynote-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daynote-backend
  template:
    metadata:
      labels:
        app: daynote-backend
    spec:
      containers:
        - name: daynote-backend
          image: ghcr.io/steve-shih/daynotehtml-daynote-backend:main

          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DAYNOTE_MONGO_URI
            - name: PORT
              value: "5000"
            - name: GCS_BUCKET_NAME
              value: "petpa"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/app/secrets/gcp-service-account.json"
          volumeMounts:
            - name: daynote-data
              mountPath: /app/data
            - name: gcp-key
              mountPath: "/app/secrets"
              readOnly: true
      volumes:
        - name: gcp-key
          secret:
            secretName: db-secrets
            items:
              - key: gcp-service-account.json
                path: gcp-service-account.json
        - name: daynote-data
          persistentVolumeClaim:
            claimName: daynote-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: daynote-backend
spec:
  selector:
    app: daynote-backend
  ports:
    - port: 5000
      targetPort: 5000
---
# 4. daynote-frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daynote-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daynote-frontend
  template:
    metadata:
      labels:
        app: daynote-frontend
    spec:
      containers:
        - name: daynote-frontend
          image: ghcr.io/steve-shih/daynotehtml-daynote-frontend:main

          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: daynote-frontend
spec:
  selector:
    app: daynote-frontend
  ports:
    - port: 3000
      targetPort: 3000
---
# 5. Pet Adoption
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-adoption
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-adoption
  template:
    metadata:
      labels:
        app: pet-adoption
    spec:
      containers:
        - name: pet-adoption
          image: ghcr.io/steve-shih/pet-adoption-signing-pet-adoption:main

          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: PET_MONGODB_URI
          
          volumeMounts:
            - name: pet-data
              mountPath: /app/data

      volumes:
        - name: pet-data
          persistentVolumeClaim:
            claimName: pet-adoption-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: pet-adoption
spec:
  selector:
    app: pet-adoption
  ports:
    - port: 5000
      targetPort: 5000

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: daynote-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pet-adoption-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: erp-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - erp.wheel.petpa.tw
    secretName: erp-tls
  rules:
  - host: erp.wheel.petpa.tw
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tire-erp
            port:
              number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: area-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - area.petpa.tw
    secretName: area-tls
  rules:
  - host: area.petpa.tw
    http:
      paths:
      - path: /daynote/api/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: daynote-backend
            port:
              number: 5000
      - path: /daynote/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: daynote-frontend
            port:
              number: 3000
      - path: /feeding/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: feeding
            port:
              number: 3000
      - path: /petlive/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: pet-adoption
            port:
              number: 5000
