# ==============================================================================
# æª”æ??ç¨± (File): prod/tire-erp.yaml
# è² è²¬?ƒä»¶ (Component): Tire ERP ç³»çµ±
# æª”æ??¨é€?(Purpose): å®šç¾©?Ÿç”¢?°å? Tire ERP ??Deployment?Service ?‡å?å±?Ingress??# ?œè¯è¨­å? (Dependencies): ä¾è³´ tire-erp namespace ä¸­ç? db-secrets ??erp-tls ?‘è???# ==============================================================================
apiVersion: v1
kind: Namespace
metadata:
  name: tire-erp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tire-erp
  namespace: tire-erp
spec:
  replicas: 0
  selector:
    matchLabels:
      app: tire-erp
  template:
    metadata:
      labels:
        app: tire-erp
    spec:
      containers:
        - name: tire-erp
          image: ghcr.io/steve-shih/tire_erp-tire-erp:master
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: TIRE_ERP_MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: tire-erp
  namespace: tire-erp
spec:
  selector:
    app: tire-erp
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: erp-ingress
  namespace: tire-erp
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - erp.wheel.petpa.tw
    secretName: erp-tls
  rules:
  - host: erp.wheel.petpa.tw
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tire-erp
            port:
              number: 8000
